version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=bare_user
      - POSTGRES_PASSWORD=bare_pass
      - POSTGRES_DB=bare_minimum
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
